[32m2024-01-17 11:35:40 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - f55d5f4d-3b72-44dc-a8d7-5b9c54d89579 - 59438 - LOGS_CAPTURED - Started capturing logs in process (pid: 59438).
[32m2024-01-17 11:35:40 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - f55d5f4d-3b72-44dc-a8d7-5b9c54d89579 - 59438 - seasons_df - STEP_START - Started execution of step "seasons_df".
[32m2024-01-17 11:35:42 +0100[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - f55d5f4d-3b72-44dc-a8d7-5b9c54d89579 - 59438 - seasons_df - STEP_FAILURE - Execution of step "seasons_df" failed.

dagster._core.errors.DagsterExecutionInterruptedError

Stack Trace:
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_plan.py", line 286, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 487, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 169, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 95, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 212, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 181, in _yield_compute_results
    for event in iterate_with_context(
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 467, in iterate_with_context
    next_output = next(iterator)
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/Users/ilyapetruhnov/Documents/Projects/fanareas/fanareas/fanareas/assets/assets.py", line 9, in seasons_df
    df = fetch_data(f"{base_url}/seasons")
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/definitions/op_definition.py", line 456, in __call__
    return direct_invocation_result(self, *args, **kwargs)
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/definitions/op_invocation.py", line 211, in direct_invocation_result
    result = invoke_compute_fn(
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/Users/ilyapetruhnov/Documents/Projects/fanareas/fanareas/fanareas/ops/utils.py", line 58, in fetch_data
    result = api_call(api_url)
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/definitions/op_definition.py", line 456, in __call__
    return direct_invocation_result(self, *args, **kwargs)
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/definitions/op_invocation.py", line 197, in direct_invocation_result
    bound_context = (context or build_op_context()).bind(
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/execution/context/invocation.py", line 782, in build_op_context
    return UnboundOpExecutionContext(
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/execution/context/invocation.py", line 93, in __init__
    self._instance = self._exit_stack.enter_context(ephemeral_instance_if_missing(instance))
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/contextlib.py", line 492, in enter_context
    result = _cm_type.__enter__(cm)
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/execution/api.py", line 292, in ephemeral_instance_if_missing
    with DagsterInstance.ephemeral() as ephemeral_instance:
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/instance/__init__.py", line 519, in ephemeral
    run_storage=InMemoryRunStorage(preload=preload),
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/storage/runs/in_memory.py", line 35, in __init__
    stamp_alembic_rev(alembic_config, self._held_conn)
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/storage/sql.py", line 68, in stamp_alembic_rev
    stamp(alembic_config, rev)
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/alembic/command.py", line 690, in stamp
    script.run_env()
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/storage/alembic/env.py", line 16, in <module>
    run_migrations_online(context, config, target_metadata)  # type: ignore  # (bad stubs)
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_core/storage/sql.py", line 145, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/alembic/runtime/migration.py", line 615, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/alembic/command.py", line 678, in do_stamp
    return script._stamp_revs(util.to_tuple(destination_revs), rev)
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/alembic/script/base.py", line 498, in _stamp_revs
    self.revision_map.filter_for_lineage(
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/alembic/script/revision.py", line 693, in filter_for_lineage
    id_, branch_label = self._resolve_revision_number(check_against)
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/alembic/script/revision.py", line 767, in _resolve_revision_number
    self._revision_map
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 1146, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/alembic/script/revision.py", line 210, in _revision_map
    for revision in self._generator():
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/alembic/script/base.py", line 144, in _load_revisions
    real_path = os.path.realpath(file_path)
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/posixpath.py", line 396, in realpath
    path, ok = _joinrealpath(filename[:0], filename, strict, {})
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/posixpath.py", line 431, in _joinrealpath
    st = os.lstat(newpath)
  File "/Users/ilyapetruhnov/opt/miniconda3/envs/fanareas/lib/python3.10/site-packages/dagster/_utils/interrupts.py", line 82, in _new_signal_handler
    raise error_cls()
[0m
